services:
  db:
    image: mysql:8.0
    container_name: lexcontrol-db
    environment:
      MYSQL_DATABASE: lexcontrol_db
      MYSQL_ROOT_PASSWORD: En648213!
    ports:
      - "3310:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lexcontrol-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lexcontrol_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: En648213!